@startuml "Hello Participants"

footer Designed & Developed by Jawahar Balachandher\nB.Tech CSE, 2025 Batch\nPES University, Electronics City Campus, Bangalore
title "Don't Cheat"
actor Alice
actor Bob 
Alice -> Bob: I like 32 , sometimes I like 64
Bob -> Alice: I like 64, sometimes I like 32

Alice -> Bob: JBSXSLBAIFZGKIDZN52SAZLONJXXS2LOM4QGWYLMOBQW4YJAGIYDENBAH4QA==== 
Bob -> Alice: WWVzLCBpdHMgdHJ1ZWx5IGFtYXppbmcu
Alice -> Bob: KNUGC3DMEB3WKIDFPBRWQYLOM5SSAZTMMFTXGIDUN4QGE33PON2CA5LQEBXXK4RAOJQW42ZANFXCA5DIMUQGYZLBMRSXEYTPMFZGIIB7
Bob -> Alice: U3VyZSwgbGV0cyBkbyBpdC4gQnV0IGtlZXAgb3VyIGNvbnZlcnNhdGlvbiBzZWNyZXQgZnJvbSBub3cu
Alice -> Bob: IZUXE43UEBUGC3DGEBXWMIDUNBSSAZTMMFTSA2LTHIQFGMSGONRUORTVLFMHGM3BIRHGMYTKKJ2E2MJYO5NGYOB5
Bob -> Alice: SSBsb29rIGZvciB0aGUgcmVzdC4=
Alice -> Bob: KRUGKIDNNFSGI3DFEBYGC4TUEBUXGIDWMVZHSIDIMFZGIIDUN4QGM2LOMQXA==== 
Bob -> Alice: U28sIGxldHMgZG8gb25lIHRoaW5nIHRoZW4sIEknbGwgZmluZCB0aGUgbWlkZGxlIHBhcnQuIFlvdSB0cnkgZm9yIHRoZSBmaW5hbCBwYXJ0IG9mIHRoZSBmbGFn
Alice -> Bob: I5XW6ZBAOBWGC3RMEBWGK5DTE4QGOZLUEBRXEYLDNNUW4JY=
Bob -> Alice: T0sgIQ==
Alice -> Bob: JEQGM33VNZSCA5DIMUQGYYLTOQQHAYLSOQQG6ZRAORUGKIDGNRQWOORALAZUC6COI42TAZCXGB4FQMSON5GTETTSLB5EMMCYPJBDCZCIGA6Q====
Bob -> Alice: Tm9pY2UsIEknbSB3b3JraW5nIG9uIGl0Lg==
Alice -> Bob: J5VSYICJE5WGYIDXMFUXILQ=
Bob -> Alice: SSBmb3VuZCB0aGUgbWlkZGxlIHBhcnQsIGl0IGlzOiBHNVVHS1gzVk5VWVY2TUpWTDQ9PT09PT0=
Alice -> Bob: I5DSAQTPMI======
Bob -> Alice: R0cgQWxpY2U=

Bob -> Alice: SSdtIHRoZSBvcmdhbml6ZXIgb2YgdGhpcyBldmVudCwgZm91bmQgdGhlIGZha2UgZmxhZz8= 
Alice -> Bob: JEQGQYLUMUQHS33V
Bob -> Alice: Tm8gcHJvYmxlbSwgeW91IGFyZSBkaXNxdWFsaWZpZWQu
Alice -> Bob: JZHW633PN5XW633PN5XW633PN5XW633PN5XW633PN5XW633PN5XW633PN5XQ====

@enduml