const easy_ans = {
    "0":"Rose Quartz",
    "1":"Peridot",
    "2":"Pearl",
    "3":"Amethyst",
    "4":"Ruby",
    "5":"Sapphire",
    "6":"Bismuth",
    "7":"Lapis Lazuli",
    "8":"Jasper",
    "9":"Obsidian",
    "10":"Rose Quartz",
    "11":"Peridot",
    "12":"Pearl",
    "13":"Amethyst",
    "14":"Ruby",
    "15":"Sapphire",
    "16":"Bismuth",
    "17":"Lapis Lazuli",
    "18":"Jasper",
    "19":"Obsidian",
}

const med_ans = {
    "0":"Larimar",
    "1":"Serpentine",
    "2":"White Diamond",
    "3":"Yellow Diamond",
    "4":"Blue Diamond",
    "5":"Pink Diamond",
    "6":"Agate",
    "7":"Flint",
    "8":"Zircons",
    "9":"Nephrite",
    "10":"Larimar",
    "11":"Serpentine",
    "12":"White Diamond",
    "13":"Yellow Diamond",
    "14":"Blue Diamond",
    "15":"Pink Diamond",
    "16":"Agate",
    "17":"Flint",
    "18":"Zircons",
    "19":"Nephrite",

}

const hard_ans = {
    "0":"Garnet",
    "1":"Opal",
    "2":"Sugilite",
    "3":"Alexandrite",
    "4":"Sardonyx",
    "5":"Sunstone",
    "6":"Malachite",
    "7":"Topaz",
    "8":"Rhodonite",
    "9":"Fluorite",
    "10":"Garnet",
    "11":"Opal",
    "12":"Sugilite",
    "13":"Alexandrite",
    "14":"Sardonyx",
    "15":"Sunstone",
    "16":"Malachite",
    "17":"Topaz",
    "18":"Rhodonite",
    "19":"Fluorite",

}

module.exports = {
    easy_ans,
    med_ans,
    hard_ans
}